from typing import List, Dict, Any

# Type definitions for structured document content and flat session content
DocumentContent = List[Dict[str, Any]]
SessionContent = List[str]


class SessionManager:
    """
    Manages the division of a large, structured document (JSON) into
    smaller, manageable study sessions.
    
    This layer assumes the JSON content has already been generated by an 
    advanced processor (e.g., an AI model).
    """

    def __init__(self, full_document_content: DocumentContent):
        """
        :param full_document_content: Complete document content in structured JSON format.
        """
        self.document_content = full_document_content

    def get_available_sessions(self) -> List[Dict[str, str]]:
        """
        Returns a list of available sessions based on the document structure.
        Currently, each chapter/title is considered a session.
        """
        sessions = []
        for i, chapter in enumerate(self.document_content):
            sessions.append({
                "session_id": f"chapter_{i}",
                "title": chapter.get("title", f"Sesión {i+1}"),
                "segment_count": len(chapter.get("segments", []))
            })
        return sessions

    def generate_session_content(self, session_id: str, max_segments: int = 50) -> SessionContent:
        """
        Extracts the content for a specific session, limiting the number of segments.
        
        :param session_id: The ID of the session to extract (e.g., 'chapter_0').
        :param max_segments: The maximum number of text segments for the session.
        :return: A flat list of strings (text segments) for the session.
        """
        
        try:
            chapter_index = int(session_id.split('_')[-1])
            chapter = self.document_content[chapter_index]
            
            segments = chapter.get("segments", [])
            
            # Apply the segment limit for manageability
            session_data = segments[:max_segments]
            
            print(f"Session '{chapter.get('title')}' generated with {len(session_data)} segments.")
            return session_data
            
        except (IndexError, ValueError) as e:
            print(f"❌ Error generating session content for {session_id}: {e}")
            return []

# Example of the structured JSON content expected by the manager
EXAMPLE_DOCUMENT_JSON: DocumentContent = [
    {
        "title": "Capítulo 1: Introducción a la IA",
        "segments": [
            "La Inteligencia Artificial (IA) es un campo de la informática dedicado a la resolución de problemas.",
            "Los sistemas de IA buscan imitar la cognición humana, incluyendo el aprendizaje y la toma de decisiones.",
            "Los subcampos principales son el Machine Learning, Deep Learning y Procesamiento de Lenguaje Natural (NLP)."
        ]
    },
    {
        "title": "Capítulo 2: Tipos de Modelos",
        "segments": [
            "Los modelos supervisados aprenden de datos etiquetados, como clasificación y regresión.",
            "Los modelos no supervisados buscan patrones en datos sin etiquetar, como el clustering.",
            "El Aprendizaje por Refuerzo se centra en agentes que toman decisiones para maximizar recompensas en un entorno."
        ]
    }
]
