from typing import List, Dict, Any
import json
import os
import math
from backend.core.db_manager import db_manager # Importar el db_manager global

# Type definitions for structured document content and flat session content
DocumentContent = List[Dict[str, Any]]
SessionContent = List[str]


class SessionManager:
    """
    Manages the division of a large, structured document (JSON) into
    smaller, manageable study sessions.
    
    This layer assumes the JSON content has already been generated by an 
    advanced processor (e.g., an AI model).
    """

    def __init__(self, full_document_content: DocumentContent):
        """
        :param full_document_content: Complete document content in structured JSON format.
        """
        self.document_content = full_document_content

    def _flatten_all_segments(self) -> List[str]:
        """
        Extracts all segments from all chapters into a single flat list.
        """
        all_segments = []
        for chapter in self.document_content:
            all_segments.extend(chapter.get("segments", []))
        return all_segments

    def create_and_store_sessions_by_segments(
        self, 
        user_id: int, 
        document_id: int, 
        segments_per_session: int
    ) -> List[Dict[str, Any]]:
        """
        Divides the document into sessions based on a fixed number of segments,
        saves each session as a separate JSON file, and registers it in the DB.
        
        :param user_id: ID of the user owning the session.
        :param document_id: ID of the parent document.
        :param segments_per_session: The 'n' value for chunking.
        :return: A list of dictionaries containing metadata of created sessions.
        """
        
        all_segments = self._flatten_all_segments()
        if not all_segments:
            print("⚠️ No segments found in the document content.")
            return []

        num_sessions = math.ceil(len(all_segments) / segments_per_session)
        created_sessions = []
        
        conn = db_manager.get_connection()
        cursor = conn.cursor()

        try:
            for i in range(num_sessions):
                start_index = i * segments_per_session
                end_index = start_index + segments_per_session
                
                # Obtener el chunk de segmentos
                session_segments = all_segments[start_index:end_index]
                
                session_title = f"Document {document_id} - Part {i+1}"
                
                # Crear el contenido del "SUBJSON"
                session_data = {
                    "title": session_title,
                    "segments": session_segments
                }
                
                # Generar ruta y nombre de archivo
                filename = f"doc{document_id}_user{user_id}_session{i+1}.json"
                filepath = os.path.join(db_manager.DOC_STORAGE_PATH, filename)
                
                # 1. Guardar el archivo "SUBJSON" localmente
                try:
                    with open(filepath, 'w', encoding='utf-8') as f:
                        json.dump(session_data, f, ensure_ascii=False, indent=4)
                except IOError as e:
                    print(f"❌ Error saving session file {filepath}: {e}")
                    continue # Saltar esta sesión si falla el guardado
                    
                # 2. Registrar la sesión en la BBDD
                cursor.execute(
                    """
                    INSERT INTO study_sessions 
                    (user_id, document_id, title, session_json_path, segment_count)
                    VALUES (?, ?, ?, ?, ?)
                    """,
                    (user_id, document_id, session_title, filepath, len(session_segments))
                )
                
                session_id = cursor.lastrowid
                created_sessions.append({
                    "session_id": session_id,
                    "title": session_title,
                    "segment_count": len(session_segments),
                    "path": filepath
                })
            
            conn.commit()
            print(f"✅ Successfully created and stored {len(created_sessions)} sessions.")
            
        except Exception as e:
            conn.rollback()
            print(f"❌ Error creating sessions in DB: {e}")
        finally:
            conn.close()
            
        return created_sessions


# Example of the structured JSON content expected by the manager
EXAMPLE_DOCUMENT_JSON: DocumentContent = [
    {
        "title": "Capítulo 1: Introducción a la IA",
        "segments": [
            "La Inteligencia Artificial (IA) es un campo de la informática dedicado a la resolución de problemas.",
            "Los sistemas de IA buscan imitar la cognición humana, incluyendo el aprendizaje y la toma de decisiones.",
            "Los subcampos principales son el Machine Learning, Deep Learning y Procesamiento de Lenguaje Natural (NLP)."
        ]
    },
    {
        "title": "Capítulo 2: Tipos de Modelos",
        "segments": [
            "Los modelos supervisados aprenden de datos etiquetados, como clasificación y regresión.",
            "Los modelos no supervisados buscan patrones en datos sin etiquetar, como el clustering.",
            "El Aprendizaje por Refuerzo se centra en agentes que toman decisiones para maximizar recompensas en un entorno."
        ]
    }
]
