from fastapi import APIRouter, HTTPException, Depends, status
from pydantic import BaseModel, Field
from typing import Dict, Any, Literal, List, Annotated
import json
import os
import sqlite3

from backend.core.session_manager import SessionManager
from backend.services.study_service import StudyService, AVAILABLE_METHODS
from backend.services.user_service import UserService, user_service 
from backend.core.db_manager import db_manager


# --- Pydantic Models: User Auth ---

class UserRegisterRequest(BaseModel):
    email: str = Field(..., description="Email for registration.")
    password: str = Field(..., description="Password for registration.")
    name: str = Field(..., description="User's name.")

class UserLoginRequest(BaseModel):
    email: str = Field(..., description="Email for login.")
    password: str = Field(..., description="Password for login.")
    
class UserAuthResponse(BaseModel):
    user_id: int
    email: str
    name: str

# --- Pydantic Models: Study Session ---

class CreateSessionsRequest(BaseModel):
    segments_per_session: int = Field(..., gt=0, description="Number of segments 'n' for each session chunk.")

class StudySessionInfo(BaseModel):
    id: int
    title: str
    segment_count: int
    created_at: str

class StartStudyRequest(BaseModel):
    """Defines the payload required to start a study session."""
    session_content: List[str] = Field(..., description="Study session content (list of text fragments) generated by the Session Manager.")
    
    method_name: Literal["read_repeat"] = Field(..., description="The name of the study method to use.")
    method_config: Dict[str, Any] = Field(
        {"repeat_delay_seconds": 5}, 
        description="Configuration specific to the chosen method."
    )

class StudyStatusResponse(BaseModel):
    """Defines the response structure for the status endpoint."""
    is_active: bool = Field(..., description="True if a study session is currently running.")
    current_method: str | None = Field(None, description="The name of the currently active method, if any.")

class MethodListResponse(BaseModel):
    """Defines the response structure for listing available methods."""
    methods: Dict[str, str] = Field(..., description="A map of method names to their descriptions.")


# --- Dependencies ---

def get_user_service() -> UserService:
    return user_service

UserDep = Annotated[UserService, Depends(get_user_service)]

# --- API Router ---
router = APIRouter(prefix="/study", tags=["Study & Auth"])

# Global service instances
study_service = StudyService()


# --- User Authentication Endpoints ---

@router.post("/register", status_code=status.HTTP_201_CREATED, response_model=UserAuthResponse)
async def register_user(request: UserRegisterRequest, user_service: UserDep):
    """
    Registers a new user and returns user ID and details.
    """
    user_data = user_service.register_user(request.email, request.password, request.name)
    
    if not user_data:
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail="User already exists or failed to register."
        )
    
    return UserAuthResponse(**user_data)


@router.post("/login", response_model=UserAuthResponse)
async def login_user(request: UserLoginRequest, user_service: UserDep):
    """
    Authenticates a user and returns their details.
    """
    user_data = user_service.login_user(request.email, request.password)
    
    if user_data:
        return UserAuthResponse(**user_data)
    
    raise HTTPException(
        status_code=status.HTTP_401_UNAUTHORIZED,
        detail="Invalid email or password"
    )

# --- Session Management Endpoints ---

@router.post("/documents/{document_id}/create-sessions", response_model=List[Dict[str, Any]])
def create_study_sessions(document_id: int, request: CreateSessionsRequest):
    """
    Generates and stores study sessions for a document based on segment count.
    """
    conn = db_manager.get_connection()
    cursor = conn.cursor()
    
    # 1. Get the main JSON path and user_id for the document
    cursor.execute("SELECT json_file_path, user_id FROM documents WHERE id = ?", (document_id,))
    doc_data = cursor.fetchone()
    conn.close()
    
    if not doc_data:
        raise HTTPException(status_code=404, detail="Document not found.")
        
    json_file_path, user_id = doc_data
    
    if not os.path.exists(json_file_path):
        raise HTTPException(status_code=404, detail="Document JSON file not found on server.")

    # 2. Load the main document content
    try:
        with open(json_file_path, 'r', encoding='utf-8') as f:
            full_content = json.load(f)
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to read document JSON: {e}")

    # 3. Instantiate manager and create/store sessions
    manager = SessionManager(full_content)
    new_sessions = manager.create_and_store_sessions_by_segments(
        user_id=user_id,
        document_id=document_id,
        segments_per_session=request.segments_per_session
    )
    
    return new_sessions


@router.get("/documents/{document_id}/sessions", response_model=List[StudySessionInfo])
def get_document_sessions(document_id: int):
    """
    Returns a list of all available study sessions generated for a specific document.
    """
    conn = db_manager.get_connection()
    conn.row_factory = sqlite3.Row # To get results as dicts
    cursor = conn.cursor()
    
    cursor.execute(
        "SELECT id, title, segment_count, created_at FROM study_sessions WHERE document_id = ?",
        (document_id,)
    )
    sessions = [dict(row) for row in cursor.fetchall()]
    conn.close()
    
    if not sessions:
        raise HTTPException(status_code=404, detail="No study sessions found for this document.")
        
    return sessions


@router.get("/sessions/{session_id}", response_model=List[str])
def get_session_content(session_id: int):
    """
    Returns the content (list of strings) for a specific session ID
    by reading its generated JSON file.
    """
    conn = db_manager.get_connection()
    cursor = conn.cursor()
    
    # 1. Find the session's JSON file path
    cursor.execute("SELECT session_json_path FROM study_sessions WHERE id = ?", (session_id,))
    session_data = cursor.fetchone()
    conn.close()
    
    if not session_data:
        raise HTTPException(status_code=404, detail=f"Session ID '{session_id}' not found.")
        
    session_json_path = session_data[0]
    
    if not os.path.exists(session_json_path):
        raise HTTPException(status_code=404, detail="Session JSON file not found on server. It may have been moved or deleted.")

    # 2. Load the session content from its specific JSON
    try:
        with open(session_json_path, 'r', encoding='utf-8') as f:
            content_data = json.load(f)
            
        segments = content_data.get("segments", [])
        if not segments:
            raise HTTPException(status_code=404, detail="Session file is empty or missing 'segments'.")
            
        return segments
            
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to read session JSON: {e}")


# --- Study Execution Endpoints ---

@router.post("/start", response_model=StudyStatusResponse)
def start_study(request: StartStudyRequest):
    """
    Starts a new study session in the background using the specified method and content.
    """
    success = study_service.start_study_session(
        session_content=request.session_content,
        method_name=request.method_name,
        method_config=request.method_config
    )
    
    if success:
        current_method_name = study_service.current_method.name if study_service.current_method else request.method_name
        return StudyStatusResponse(
            is_active=True,
            current_method=current_method_name
        )
    else:
        raise HTTPException(
            status_code=409, # Conflict
            detail="Failed to start study session. A session may already be active."
        )


@router.post("/stop", response_model=StudyStatusResponse)
def stop_study():
    """
    Requests the active study session to stop gracefully.
    """
    study_service.stop_study_session()
    return StudyStatusResponse(is_active=False, current_method=None)


@router.get("/status", response_model=StudyStatusResponse)
def get_study_status():
    """
    Retrieves the current status of the study application.
    """
    current_method_name = study_service.current_method.name if study_service.current_method else None
    
    return StudyStatusResponse(
        is_active=study_service.is_session_active,
        current_method=current_method_name
    )


@router.get("/methods", response_model=MethodListResponse)
def list_available_methods():
    """
    Lists all implemented study methods available for use.
    """
    method_descriptions = {
        name: method_cls(None, [], {}).name # Pass dummy args
        for name, method_cls in AVAILABLE_METHODS.items()
    }
    return MethodListResponse(methods=method_descriptions)

