from fastapi import APIRouter, HTTPException, Depends, status, UploadFile, File, Form
from pydantic import BaseModel, Field
from typing import Dict, Any, Literal, List, Annotated
import json
import os
import sqlite3
import shutil
import tempfile

from backend.core.session_manager import SessionManager
from backend.services.study_service import StudyService, AVAILABLE_METHODS
from backend.services.user_service import UserService, user_service 
from backend.core.db_manager import db_manager
from backend.core.document_processor import process_pdf_to_json


# --- Pydantic Models: User Auth ---

class UserRegisterRequest(BaseModel):
    email: str = Field(..., description="Email for registration.")
    password: str = Field(..., description="Password for registration.")
    name: str = Field(..., description="User's name.")

class UserLoginRequest(BaseModel):
    email: str = Field(..., description="Email for login.")
    password: str = Field(..., description="Password for login.")
    
class UserAuthResponse(BaseModel):
    user_id: int
    email: str
    name: str

# --- Pydantic Models: Document and Study Session ---

class DocumentUploadResponse(BaseModel):
    document_id: int = Field(..., description="The ID of the newly uploaded and processed document.")
    title: str = Field(..., description="The title of the document as determined by the AI model.")
    message: str = Field("Document processed and saved successfully.", description="Confirmation message.")

class CreateSessionsRequest(BaseModel):
    segments_per_session: int = Field(..., gt=0, description="Number of segments 'n' for each session chunk.")

class StudySessionInfo(BaseModel):
    id: int
    title: str
    segment_count: int
    created_at: str

class StartStudyRequest(BaseModel):
    """Defines the payload required to start a study session."""
    session_content: List[str] = Field(..., description="Study session content (list of text fragments) generated by the Session Manager.")
    
    method_name: Literal["read_repeat"] = Field(..., description="The name of the study method to use.")
    method_config: Dict[str, Any] = Field(
        {"repeat_delay_seconds": 5}, 
        description="Configuration specific to the chosen method."
    )

class StudyStatusResponse(BaseModel):
    """Defines the response structure for the status endpoint."""
    is_active: bool = Field(..., description="True if a study session is currently running.")
    current_method: str | None = Field(None, description="The name of the currently active method, if any.")

class MethodListResponse(BaseModel):
    """Defines the response structure for listing available methods."""
    methods: Dict[str, str] = Field(..., description="A map of method names to their descriptions.")


# --- Dependencies ---

def get_user_service() -> UserService:
    return user_service

UserDep = Annotated[UserService, Depends(get_user_service)]

# --- Mock Dependency for User ID ---
def get_current_user_id() -> int:
    """Mock function to simulate getting the authenticated user's ID."""
    # Use 1 as a mock ID. This must be replaced with real authentication.
    return 1

UserAuthDep = Annotated[int, Depends(get_current_user_id)]


# --- API Router ---
router = APIRouter(prefix="/study", tags=["Study & Auth"])

# Global service instances
study_service = StudyService()


# --- User Authentication Endpoints ---

@router.post("/register", status_code=status.HTTP_201_CREATED, response_model=UserAuthResponse)
async def register_user(request: UserRegisterRequest, user_service: UserDep):
    """Registers a new user and returns user ID and details."""
    user_data = user_service.register_user(request.email, request.password, request.name)
    
    if not user_data:
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail="User already exists or failed to register."
        )
    
    return UserAuthResponse(**user_data)


@router.post("/login", response_model=UserAuthResponse)
async def login_user(request: UserLoginRequest, user_service: UserDep):
    """Authenticates a user and returns their details."""
    user_data = user_service.login_user(request.email, request.password)
    
    if user_data:
        return UserAuthResponse(**user_data)
    
    raise HTTPException(
        status_code=status.HTTP_401_UNAUTHORIZED,
        detail="Invalid email or password"
    )

# --- Document Upload Endpoint ---

@router.post("/upload-document", response_model=DocumentUploadResponse, status_code=status.HTTP_201_CREATED)
async def upload_document(
    file: UploadFile = File(..., description="The PDF file to be processed."),
    user_id: int = Depends(get_current_user_id)  
):
    """
    Handles the upload of a PDF file, processes it with the AI model to extract 
    structured JSON, and saves the result to the database and file system.
    """
    if file.content_type != 'application/pdf':
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Only PDF files are allowed.")
    
    # 1. Save the uploaded file temporarily
    with tempfile.NamedTemporaryFile(delete=False, suffix=".pdf") as tmp:
        try:
            # Write the UploadFile content to the temporary file
            shutil.copyfileobj(file.file, tmp)
            temp_path = tmp.name
        finally:
            file.file.close()

    document_title = file.filename.replace('.pdf', '')
    
    try:
        # 2. Process the PDF using the Gemini API
        structured_json_data = process_pdf_to_json(user_pdf_path=temp_path)
        
        if structured_json_data is None:
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, 
                detail="AI processing failed or returned invalid data. Check API Key and logs."
            )
            
        # 3. Get the final title from the AI output
        final_title = structured_json_data.get('title', document_title)

        # 4. Save the document JSON and record in the database
        new_doc_id = db_manager.save_document_json(
            user_id=user_id,  
            title=final_title,
            json_data=structured_json_data
        )
        
        if new_doc_id is None:
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail="Failed to save document record to the database."
            )

        return DocumentUploadResponse(document_id=new_doc_id, title=final_title)

    except HTTPException as e:
        raise e
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, 
            detail=f"An unexpected error occurred during document processing: {e}"
        )
    finally:
        # 5. Cleanup: Delete the local temporary file
        if os.path.exists(temp_path):
            os.remove(temp_path)
            print(f"Temporary file {temp_path} deleted from local system.")

# --- Session Management Endpoints ---

@router.post("/documents/{document_id}/create-sessions", response_model=List[Dict[str, Any]])
def create_study_sessions(document_id: int, request: CreateSessionsRequest):
    """Generates and stores study sessions for a document based on segment count."""
    conn = db_manager.get_connection()
    cursor = conn.cursor()
    
    # 1. Get the main JSON path and user_id for the document
    cursor.execute("SELECT json_file_path, user_id FROM documents WHERE id = ?", (document_id,))
    doc_data = cursor.fetchone()
    conn.close()
    
    if not doc_data:
        raise HTTPException(status_code=404, detail="Document not found.")
        
    json_file_path, user_id = doc_data
    
    if not os.path.exists(json_file_path):
        raise HTTPException(status_code=404, detail="Document JSON file not found on server.")

    # 2. Load the main document content
    try:
        with open(json_file_path, 'r', encoding='utf-8') as f:
            full_content = json.load(f)
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to read document JSON: {e}")

    # 3. Instantiate manager and create/store sessions
    manager = SessionManager(full_content)
    new_sessions = manager.create_and_store_sessions_by_segments(
        user_id=user_id,
        document_id=document_id,
        segments_per_session=request.segments_per_session
    )
    
    return new_sessions


@router.get("/documents/{document_id}/sessions", response_model=List[StudySessionInfo])
def get_document_sessions(document_id: int):
    """Returns a list of all available study sessions generated for a specific document."""
    conn = db_manager.get_connection()
    conn.row_factory = sqlite3.Row
    cursor = conn.cursor()
    
    cursor.execute(
        "SELECT id, title, segment_count, created_at FROM study_sessions WHERE document_id = ?",
        (document_id,)
    )
    sessions = [dict(row) for row in cursor.fetchall()]
    conn.close()
    
    if not sessions:
        raise HTTPException(status_code=404, detail="No study sessions found for this document.")
        
    return sessions


@router.get("/sessions/{session_id}", response_model=List[str])
def get_session_content(session_id: int):
    """Returns the content (list of strings) for a specific session ID."""
    conn = db_manager.get_connection()
    cursor = conn.cursor()
    
    # 1. Find the session's JSON file path
    cursor.execute("SELECT session_json_path FROM study_sessions WHERE id = ?", (session_id,))
    session_data = cursor.fetchone()
    conn.close()
    
    if not session_data:
        raise HTTPException(status_code=404, detail=f"Session ID '{session_id}' not found.")
        
    session_json_path = session_data[0]
    
    if not os.path.exists(session_json_path):
        raise HTTPException(status_code=404, detail="Session JSON file not found on server.")

    # 2. Load the session content from its specific JSON
    try:
        with open(session_json_path, 'r', encoding='utf-8') as f:
            content_data = json.load(f)
            
        segments = content_data.get("segments", [])
        if not segments:
            raise HTTPException(status_code=404, detail="Session file is empty or missing 'segments'.")
            
        return segments
            
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to read session JSON: {e}")


# --- Study Execution Endpoints ---

@router.post("/start", response_model=StudyStatusResponse)
def start_study(request: StartStudyRequest):
    """Starts a new study session in the background."""
    success = study_service.start_study_session(
        session_content=request.session_content,
        method_name=request.method_name,
        method_config=request.method_config
    )
    
    if success:
        current_method_name = study_service.current_method.name if study_service.current_method else request.method_name
        return StudyStatusResponse(
            is_active=True,
            current_method=current_method_name
        )
    else:
        raise HTTPException(
            status_code=409,
            detail="Failed to start study session. A session may already be active."
        )


@router.post("/stop", response_model=StudyStatusResponse)
def stop_study():
    """Requests the active study session to stop gracefully."""
    study_service.stop_study_session()
    return StudyStatusResponse(is_active=False, current_method=None)


@router.get("/status", response_model=StudyStatusResponse)
def get_study_status():
    """Retrieves the current status of the study application."""
    current_method_name = study_service.current_method.name if study_service.current_method else None
    
    return StudyStatusResponse(
        is_active=study_service.is_session_active,
        current_method=current_method_name
    )


@router.get("/methods", response_model=MethodListResponse)
def list_available_methods():
    """Lists all implemented study methods available for use."""
    method_descriptions = {
        name: method_cls(None, [], {}).name
        for name, method_cls in AVAILABLE_METHODS.items()
    }
    return MethodListResponse(methods=method_descriptions)
