from fastapi import APIRouter, HTTPException, Depends, status
from pydantic import BaseModel, Field
from typing import Dict, Any, Literal, List, Annotated
from backend.core.session_manager import SessionManager, EXAMPLE_DOCUMENT_JSON 
from backend.services.study_service import StudyService, AVAILABLE_METHODS
from backend.services.user_service import UserService, user_service 


# --- Pydantic Models for Request and Response Validation (User Auth) ---

class UserRegisterRequest(BaseModel):
    email: str = Field(..., description="Email for registration.")
    password: str = Field(..., description="Password for registration.")
    name: str = Field(..., description="User's name.")

class UserLoginRequest(BaseModel):
    email: str = Field(..., description="Email for login.")
    password: str = Field(..., description="Password for login.")
    
class UserAuthResponse(BaseModel):
    user_id: int
    email: str
    name: str

# --- Pydantic Models for Request and Response Validation (Study Session) ---

class StartStudyRequest(BaseModel):
    """
    Defines the payload required to start a study session. 
    It now expects the session content directly.
    """
    session_content: List[str] = Field(..., description="Study session content (list of text fragments) generated by the Session Manager.")
    
    method_name: Literal["read_repeat"] = Field(..., description="The name of the study method to use.")
    method_config: Dict[str, Any] = Field(
        {"repeat_delay_seconds": 5}, 
        description="Configuration specific to the chosen method."
    )

class StudyStatusResponse(BaseModel):
    """Defines the response structure for the status endpoint."""
    is_active: bool = Field(..., description="True if a study session is currently running.")
    current_method: str | None = Field(None, description="The name of the currently active method, if any.")

class MethodListResponse(BaseModel):
    """Defines the response structure for listing available methods."""
    methods: Dict[str, str] = Field(..., description="A map of method names to their descriptions.")


# --- Dependencies ---

# Dependency function that returns the global UserService instance
# This is what we will override in tests
def get_user_service() -> UserService:
    return user_service

# Define the type alias for clearer dependency use in path operations
UserDep = Annotated[UserService, Depends(get_user_service)]

# --- API Router ---
router = APIRouter(prefix="/study", tags=["Study & Auth"])


# --- User Authentication Endpoints ---

@router.post("/register", status_code=status.HTTP_201_CREATED, response_model=UserAuthResponse)
async def register_user(request: UserRegisterRequest, user_service: UserDep):
    """
    Registers a new user and returns user ID and details.
    """
    # Note: user_service.register_user now returns a Dict with user_id, email, name
    user_data = user_service.register_user(request.email, request.password, request.name)
    
    if not user_data:
        # 409 Conflict if email already exists
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail="User already exists or failed to register."
        )
    
    return UserAuthResponse(**user_data)


@router.post("/login", response_model=UserAuthResponse)
async def login_user(request: UserLoginRequest, user_service: UserDep):
    """
    Authenticates a user and returns their details.
    """
    user_data = user_service.login_user(request.email, request.password)
    
    if user_data:
        return UserAuthResponse(**user_data)
    
    # 401 Unauthorized if credentials are wrong
    raise HTTPException(
        status_code=status.HTTP_401_UNAUTHORIZED,
        detail="Invalid email or password"
    )

# --- Study Session Endpoints (Previous code starts here) ---

# Assuming study_service is a global instance initialized elsewhere
study_service = StudyService()
session_manager_demo = SessionManager(EXAMPLE_DOCUMENT_JSON)


@router.get("/sessions", response_model=List[Dict[str, Any]])
def get_available_sessions():
    """
    Returns a list of available study sessions (chapters/sections) from the demo content.
    """
    return session_manager_demo.get_available_sessions()


@router.get("/sessions/{session_id}", response_model=List[str])
def get_session_content(session_id: str):
    """
    Returns the content (list of strings) for a specific session ID.
    """
    # NOTE: In a real app, this would fetch from the DB based on user_id and document_id.
    # For now, it uses the hardcoded EXAMPLE_DOCUMENT_JSON.
    max_segments = 50 # Limit the size for the demo
    content = session_manager_demo.generate_session_content(session_id, max_segments)
    
    if not content:
        raise HTTPException(status_code=404, detail=f"Session ID '{session_id}' not found or empty.")
        
    return content


@router.post("/start", response_model=StudyStatusResponse)
def start_study(request: StartStudyRequest):
    """
    Starts a new study session in the background using the specified method and content.
    """
    
    # Validation is already handled by Pydantic models and the method list
    
    success = study_service.start_study_session(
        session_content=request.session_content,
        method_name=request.method_name,
        method_config=request.method_config
    )
    
    if success:
        # Get the name of the method that actually started
        current_method_name = study_service.current_method.name if study_service.current_method else request.method_name
        return StudyStatusResponse(
            is_active=True,
            current_method=current_method_name
        )
    else:
        # If the service failed to start (e.g., another session is active)
        raise HTTPException(
            status_code=409, # Conflict
            detail="Failed to start study session. A session may already be active."
        )


@router.post("/stop", response_model=StudyStatusResponse)
def stop_study():
    """
    Requests the active study session to stop gracefully.
    """
    study_service.stop_study_session()
    
    # Returns the desired stopped state
    return StudyStatusResponse(is_active=False, current_method=None)


@router.get("/status", response_model=StudyStatusResponse)
def get_study_status():
    """
    Retrieves the current status of the study application.
    """
    current_method_name = study_service.current_method.name if study_service.current_method else None
    
    return StudyStatusResponse(
        is_active=study_service.is_session_active,
        current_method=current_method_name
    )


@router.get("/methods", response_model=MethodListResponse)
def list_available_methods():
    """
    Lists all implemented study methods available for use.
    """
    # We instantiate the class just to get its user-friendly name property
    method_descriptions = {
        name: method_cls(None, [], {}).name # We pass dummy args as they are not used in __init__ for name
        for name, method_cls in AVAILABLE_METHODS.items()
    }
    return MethodListResponse(methods=method_descriptions)
